name: CI/CD Pipeline

on:
 push:
  branches:
   - main
 pull_request:
  branches:
   - main

jobs:
 build-and-push:
  name: Construire et pousser une image Docker
  runs-on: ubuntu-latest

  steps:
   - name: Récupérer le code source
     uses: actions/checkout@v4

   - name: Installer JDK 17
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'

   - name: Compiler avec Maven
     run: mvn clean package -DskipTests

   - name: Construire l'image Docker
     run: docker build -t diambarsene/api-backend-toure-mbonde:v01 .

   - name: Connexion à Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

   - name: Pousser l'image sur Docker Hub
     uses: docker/build-push-action@v5
     with:
      context: .
      push: true
      tags: diambarsene/api-backend-toure-mbonde:v01

 deploy:
  name: Déployer sur un VPS
  needs: build-and-push
  runs-on: ubuntu-latest

  steps:
   - name: Récupérer le code source
     uses: actions/checkout@v4

   - name: Vérifier l'existence du répertoire sur le VPS
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: ${{ secrets.SSH_PORT }}
      script: mkdir -p /docker-compose-files

   - name: Transférer docker-compose.yml sur le VPS
     uses: appleboy/scp-action@master
     with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: ${{ secrets.SSH_PORT }}
      source: "./docker-compose.yml"
      target: "/docker-compose-files"

   - name: Déployer l'application sur le VPS
     uses: appleboy/ssh-action@master
     with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      port: ${{ secrets.SSH_PORT }}
      script: |
       docker pull diambarsene/api-backend-toure-mbonde:v01
       cd /docker-compose-files
       docker-compose down
       docker-compose up -d